spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: bookWiseOnline
      password: enilinOesiWkooB

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false