spring:
  application:
    name: books
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
      active: test

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://bookWiseOnline:enilinOesiWkooB@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    book-reserve: book-reserve

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log